exports.LINE_FILE_ADAPTOR_MODELS = {
  CMS_MANIFEST_BODY: {
    key: 'CMS_MANIFEST_BODY',
    name: '清单表体模板',
    columns: [{
      field: 'product_no',
      label: '商品货号',
    }, {
      field: 'prdt_item_no',
      label: '项号',
    }, {
      field: 'hscode',
      label: '商品编码',
    }, {
      field: 'g_name',
      label: '商品名称',
    }, {
      field: 'en_name',
      label: '英文描述',
    }, {
      field: 'g_model',
      label: '规格型号',
    }, {
      field: 'element',
      label: '申报要素',
    }, {
      field: 'g_qty',
      label: '申报数量',
    }, {
      field: 'g_unit',
      label: '申报单位',
    }, {
      field: 'unit_price',
      label: '申报单价',
    }, {
      field: 'amount',
      label: '申报总价',
    }, {
      field: 'currency',
      label: '币制',
    }, {
      field: 'qty_1',
      label: '法定第一数量',
    }, {
      field: 'unit_1',
      label: '法定第一单位',
    }, {
      field: 'qty_2',
      label: '法定第二数量',
    }, {
      field: 'unit_2',
      label: '法定第二单位',
    }, {
      field: 'duty_mode',
      label: '征免方式',
    }, {
      field: 'dest_country',
      label: '目的国',
    }, {
      field: 'orig_country',
      label: '原产国',
    }, {
      field: 'qty_pcs',
      label: '数量(个数)',
    }, {
      field: 'unit_pcs',
      label: '单位(个数)',
    }, {
      field: 'net_wt',
      label: '净重(千克)',
    }, {
      field: 'gross_wt',
      label: '毛重(千克)',
    }, {
      field: 'version_no',
      label: '版本号',
    }, {
      field: 'processing_fees',
      label: '工缴费',
    }],
  },
  CWM_SHIPPING_ORDER: {
    key: 'CWM_SHIPPING_ORDER',
    name: 'SO模版',
    columns: [{
      field: 'owner_code',
      label: '客户代码',
    }, {
      field: 'cust_order_no',
      label: '客户订单号',
    }, {
      field: 'product_no',
      label: '商品货号',
    }, {
      field: 'name',
      label: '品名',
    }, {
      field: 'order_qty',
      label: '数量',
    }, {
      field: 'virtual_whse',
      label: '库别',
    }, {
      field: 'po_no',
      label: '进库订单号',
    }, {
      field: 'external_no',
      label: '批次号',
    }, {
      field: 'serial_no',
      label: '产品序列号',
    }, {
      field: 'receiver_name',
      label: '收货方',
    }, {
      field: 'receiver_contact',
      label: '联系人',
    }, {
      field: 'receiver_address',
      label: '收件详细地址',
    }, {
      field: 'receiver_phone',
      label: '联系电话',
    }, {
      field: 'receiver_number',
      label: '手机号',
    }, {
      field: 'receiver_post_code',
      label: '邮政编码',
    }, {
      field: 'expect_shipping_date',
      label: '要求出货日期',
    }, {
      field: 'bonded',
      label: '货物属性',
    }, {
      field: 'amount',
      label: '金额',
    }, {
      field: 'bonded_outtype',
      label: '监管方式',
    }, {
      field: 'supplier',
      label: '供货商',
    }],
  },
};
