exports.LINE_FILE_ADAPTOR_MODELS = {
  CMS_MANIFEST_BODY: {
    key: 'CMS_MANIFEST_BODY',
    name: '清单表体模板',
    columns: [{
      field: 'product_no',
      label: '商品货号',
    }, {
      field: 'prdt_item_no',
      label: '项号',
    }, {
      field: 'hscode',
      label: '商品编码',
    }, {
      field: 'g_name',
      label: '商品名称',
    }, {
      field: 'en_name',
      label: '英文描述',
    }, {
      field: 'g_model',
      label: '规格型号',
    }, {
      field: 'element',
      label: '申报要素',
    }, {
      field: 'g_qty',
      label: '申报数量',
    }, {
      field: 'g_unit',
      label: '申报单位',
    }, {
      field: 'unit_price',
      label: '申报单价',
    }, {
      field: 'amount',
      label: '申报总价',
    }, {
      field: 'currency',
      label: '币制',
    }, {
      field: 'qty_1',
      label: '法定第一数量',
    }, {
      field: 'unit_1',
      label: '法定第一单位',
    }, {
      field: 'qty_2',
      label: '法定第二数量',
    }, {
      field: 'unit_2',
      label: '法定第二单位',
    }, {
      field: 'duty_mode',
      label: '征免方式',
    }, {
      field: 'dest_country',
      label: '目的国',
    }, {
      field: 'orig_country',
      label: '原产国',
    }, {
      field: 'qty_pcs',
      label: '数量(个数)',
    }, {
      field: 'unit_pcs',
      label: '单位(个数)',
    }, {
      field: 'net_wt',
      label: '净重(千克)',
    }, {
      field: 'gross_wt',
      label: '毛重(千克)',
    }, {
      field: 'version_no',
      label: '版本号',
    }, {
      field: 'processing_fees',
      label: '工缴费',
    }],
  },
  CWM_SHIPPING_ORDER: {
    key: 'CWM_SHIPPING_ORDER',
    name: 'SO模版',
    columns: [{
      field: 'owner_code',
      label: '客户代码',
    }, {
      field: 'cust_order_no',
      label: '客户订单号',
    }, {
      field: 'product_no',
      label: '商品货号',
    }, {
      field: 'name',
      label: '品名',
    }, {
      field: 'order_qty',
      label: '数量',
    }, {
      field: 'virtual_whse',
      label: '库别',
    }, {
      field: 'po_no',
      label: '进库订单号',
    }, {
      field: 'external_no',
      label: '批次号',
    }, {
      field: 'serial_no',
      label: '产品序列号',
    }, {
      field: 'receiver_name',
      label: '收货方',
    }, {
      field: 'receiver_contact',
      label: '联系人',
    }, {
      field: 'receiver_address',
      label: '收件详细地址',
    }, {
      field: 'receiver_phone',
      label: '联系电话',
    }, {
      field: 'receiver_number',
      label: '手机号',
    }, {
      field: 'receiver_post_code',
      label: '邮政编码',
    }, {
      field: 'expect_shipping_date',
      label: '要求出货日期',
    }, {
      field: 'bonded',
      label: '货物属性',
    }, {
      field: 'amount',
      label: '金额',
    }, {
      field: 'bonded_outtype',
      label: '监管方式',
    }, {
      field: 'supplier',
      label: '供货商',
    }],
  },
  SOF_ORDER: {
    key: 'SOF.ORDER',
    name: '订单模板',
    columns: [{
      field: 'cust_code',
      label: '客户代码',
    }, {
      field: 'cust_order_no',
      label: '客户单号(必填)',
    }, {
      field: 'cust_shipmt_transfer',
      label: '进出口标识',
    }, {
      field: 'cust_shipmt_pieces',
      label: '件数',
    }, {
      field: 'cust_shipmt_wrap_type',
      label: '包装',
    }, {
      field: 'cust_shipmt_weight',
      label: '总毛重',
    }, {
      field: 'cust_shipmt_volume',
      label: 'CBM',
    }, {
      field: 'cust_shipmt_expedited',
      label: '是否紧急',
    }, {
      field: 'cust_shipmt_goods_type',
      label: '货物类型',
    }, {
      field: 'cust_receiver_code',
      label: '收货方代码',
    }, {
      field: 'cust_receiver_name',
      label: '收货方名称',
    }, {
      field: 'cust_receiver_contact',
      label: '收货方联系人',
    }, {
      field: 'cust_receiver_address',
      label: '收件详细地址',
    }, {
      field: 'cust_receiver_tel',
      label: '收货方联系电话',
    }, {
      field: 'cust_receiver_mobile',
      label: '收货方手机号',
    }, {
      field: 'cust_remark',
      label: '备注',
    }, {
      field: 'cust_shipmt_trans_mode',
      label: '运输方式',
    }, {
      field: 'bl_mawb',
      label: '提运单/主运单',
    }, {
      field: 'swb_hawb',
      label: '海运单/分运单',
    }, {
      field: 'cust_shipmt_vessel',
      label: '船名/航班号',
    }, {
      field: 'cust_shipmt_voy',
      label: '航次',
    }, {
      field: 'cust_shipmt_forwarder',
      label: '货运代理',
    }, {
      field: 'cust_shipmt_freight',
      label: '运费',
    }, {
      field: 'cust_shipmt_freight_currency',
      label: '运费币制',
    }, {
      field: 'cust_shipmt_insur_fee',
      label: '保费',
    }, {
      field: 'cust_shipmt_insur_currency',
      label: '保费币制',
    }, {
      field: 'cust_shipmt_misc_fee',
      label: '杂费',
    }, {
      field: 'cust_shipmt_misc_currency',
      label: '杂费币制',
    }, {
      field: 'container_no',
      label: '集装箱号',
    }, {
      field: 'invoice_no',
      label: '发票号',
    }, {
      field: 'invoice_date',
      label: '发票日期',
    }, {
      field: 'po_no',
      label: '订单号',
    }, {
      field: 'product_no',
      label: '商品货号',
    }, {
      field: 'manual_no',
      label: '手册号',
    }, {
      field: 'prdt_item_no',
      label: '项号',
    }, {
      field: 'hscode',
      label: '商品编码',
    }, {
      field: 'name',
      label: '商品名称',
    }, {
      field: 'en_name',
      label: '英文描述',
    }, {
      field: 'qty',
      label: '数量(个数)',
    }, {
      field: 'unit',
      label: '单位(个数)',
    }, {
      field: 'model',
      label: '规格型号',
    }, {
      field: 'g_qty',
      label: '申报数量',
    }, {
      field: 'g_unit',
      label: '申报单位',
    }, {
      field: 'qty_1',
      label: '法定第一数量',
    }, {
      field: 'unit_1',
      label: '法定第一单位',
    }, {
      field: 'qty_2',
      label: '法定第二数量',
    }, {
      field: 'unit_2',
      label: '法定第二单位',
    }, {
      field: 'gross_wt',
      label: '毛重(千克)',
    }, {
      field: 'net_wt',
      label: '净重(千克)',
    }, {
      field: 'unit_price',
      label: '申报单价',
    }, {
      field: 'amount',
      label: '申报总价',
    }, {
      field: 'currency',
      label: '币制',
    }, {
      field: 'duty_mode',
      label: '征免方式',
    }, {
      field: 'country',
      label: '原产国',
    }, {
      field: 'dest_country',
      label: '目的国',
    }, {
      field: 'version_no',
      label: '版本号',
    }, {
      field: 'processing_fees',
      label: '工缴费',
    }, {
      field: 'trxn_mode',
      label: '成交方式',
    }, {
      field: 'virtual_whse',
      label: '库别',
    }, {
      field: 'supplier',
      label: '供货商',
    }, {
      field: 'external_lot_no',
      label: '批次号',
    }, {
      field: 'serial_no',
      label: '序列号',
    }, {
      field: 'attrib_1_string',
      label: '扩展属性1',
    }, {
      field: 'attrib_2_string',
      label: '扩展属性2',
    }, {
      field: 'attrib_3_string',
      label: '扩展属性3',
    }, {
      field: 'attrib_4_string',
      label: '扩展属性4',
    }, {
      field: 'attrib_5_string',
      label: '扩展属性5',
    }, {
      field: 'attrib_6_string',
      label: '扩展属性6',
    }, {
      field: 'attrib_7_date',
      label: '扩展属性7',
    }, {
      field: 'attrib_8_date',
      label: '扩展属性8',
    }],
  },
};
