FROM daocloud.io/welogix_tech/welogix-web-base:1.0

RUN mkdir -p /data/deploy/logs

WORKDIR /opt/apps/welogix-web
#ENV TOOL_NODE_FLAGS="--max-old-space-size=4096"

COPY .  /opt/apps/welogix-web

EXPOSE 3022
ENV NODE_ENV=production
RUN npm run docker-build

CMD [ "pm2-docker", "pm2/prod.json" ]
